### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by modmuss50** [OpenModLoader/OpenModLoader#1]
# I DID NOT WRITE THIS, IT HAS BEEN EDITED, I DISAGREE WITH IT.

# Summary
The purpose of this issue is to track progress of feature parity with Forge, in regards to the event system. If you would like to help speed up progress, please feel free to send us pull requests. If you intend to submit a pull request, please read the guidelines below. 

## Event Guidelines   

- The goal is to create feature parity between the two loaders. Under no circumstances should code by directly copied from forge. Feel free to expand upon or refactor the ideas behind the feature.
- Pull requests should only contain one event at a time. It is okay to group multiple events that are similar into one pull request. For example, all the biome color events could be in one pull request, but a block breaking event and entity update event should not.
- Seriously don't just copy forge. There are many events that are deprecated or provide duplicate functionality that should be merged together. The forge event list is just a guideline to provide feature parity, not a list of stuff for for us to add. 
- Please document your events using JavaDocs. It is expected that all fields, constructors, parameters and methods that are not inherited have JavaDocs explaining how they work. Classes should also have a JavaDoc explaining the event and its intended scope. Authorship javadocs and time stamps should not be included!
- Please comment on this post which feature you are going after, so you can "claim" it. This will help prevent multiple people from working on the same feature. 

## Event Checklist
- [ ] AnvilUpdateEvent
- [ ] AttachCapabilitiesEvent - Ignore for now
- [ ] AttachCapabilitiesEvent.Entity - Ignore for now
- [ ] AttachCapabilitiesEvent.Item - Ignore for now
- [ ] AttachCapabilitiesEvent.TileEntity - Ignore for now
- [x] BiomeEvent
- [x] BiomeEvent.BiomeColorEvent
- [x] BiomeEvent.BiomeColorEvent.GetFoliageColor
- [x] BiomeEvent.BiomeColorEvent.GetGrassColor
- [x] BiomeEvent.BiomeColorEvent.GetWaterColor
- [ ] BiomeEvent.CreateDecorator
- [ ] BiomeEvent.GetVillageBlockID
- [x] BlockEvent
- [x] BlockEvent.BreakEvent
- [x] BlockEvent.HarvestDropsEvent
- [ ] BlockEvent.NeighborNotifyEvent
- [ ] BlockEvent.NoteBlockEvent
- [ ] BlockEvent.NoteBlockEvent.Change
- [ ] BlockEvent.NoteBlockEvent.Play
- [x] BlockEvent.PlacedEvent
- [ ] BlockEvent.PlacedEvent.MultiPlaceEvent
- [ ] ChunkGeneratorEvent
- [ ] ChunkGeneratorEvent.InitNoiseField
- [ ] ChunkGeneratorEvent.PopulateChunkEvent
- [ ] ChunkGeneratorEvent.PopulateChunkEvent.Populate
- [ ] ChunkGeneratorEvent.PopulateChunkEvent.Post
- [ ] ChunkGeneratorEvent.PopulateChunkEvent.Pre
- [ ] ChunkGeneratorEvent.ReplaceBiomeBlocks
- [ ] ChunkWatchEvent
- [ ] ChunkWatchEvent.UnWatch
- [ ] ChunkWatchEvent.Watch
- [x] ClientChatReceivedEvent
- [x] CommandEvent
- [ ] ConfigChangedEvent - Ignore for now
- [ ] ConfigChangedEvent.OnConfigChangedEvent - Ignore for now
- [ ] ConfigChangedEvent.PostConfigChangedEvent - Ignore for now
- [ ] CustomNetworkEvent<T>
- [ ] DecorateBiomeEvent
- [ ] DecorateBiomeEvent.Decorate
- [ ] DecorateBiomeEvent.Post
- [ ] DecorateBiomeEvent.Pre
- [ ] DrawBlockHighlightEvent
- [x] EntityEvent
- [ ] EntityEvent.CanUpdate
- [ ] EntityEvent.EnteringChunk
- [x] EntityEvent.EntityConstructing
- [x] EntityEvent.EntityJoinWorldEvent
- [x] EntityEvent.EntityMountEvent
- [ ] EntityEvent.EntityStruckByLightningEvent
- [x] EntityEvent.EntityTravelToDimensionEvent
- [ ] EntityEvent.ItemEvent
- [ ] EntityEvent.ItemEvent.ItemExpireEvent
- [ ] EntityEvent.ItemEvent.ItemTossEvent
- [x] EntityEvent.LivingEvent
- [ ] EntityEvent.LivingEvent.EnderTeleportEvent
- [ ] EntityEvent.LivingEvent.LivingAttackEvent
- [ ] EntityEvent.LivingEvent.LivingDeathEvent
- [ ] EntityEvent.LivingEvent.LivingDropsEvent
- [ ] EntityEvent.LivingEvent.LivingDropsEvent.PlayerDropsEvent
- [ ] EntityEvent.LivingEvent.LivingEntityUseItemEvent
- [ ] EntityEvent.LivingEvent.LivingEntityUseItemEvent.Finish
- [ ] EntityEvent.LivingEvent.LivingEntityUseItemEvent.Start
- [ ] EntityEvent.LivingEvent.LivingEntityUseItemEvent.Stop
- [ ] EntityEvent.LivingEvent.LivingEntityUseItemEvent.Tick
- [ ] EntityEvent.LivingEvent.LivingExperienceDropEvent
- [x] EntityEvent.LivingEvent.LivingFallEvent
- [x] EntityEvent.LivingEvent.LivingHealEvent
- [x] EntityEvent.LivingEvent.LivingHurtEvent
- [x] EntityEvent.LivingEvent.LivingJumpEvent
- [ ] EntityEvent.LivingEvent.LivingPackSizeEvent
- [ ] EntityEvent.LivingEvent.LivingSetAttackTargetEvent
- [x] EntityEvent.LivingEvent.LivingSpawnEvent
- [x] EntityEvent.LivingEvent.LivingSpawnEvent.AllowDespawn
- [x] EntityEvent.LivingEvent.LivingSpawnEvent.CheckSpawn
- [ ] EntityEvent.LivingEvent.LivingSpawnEvent.SpecialSpawn
- [x] EntityEvent.LivingEvent.LivingUpdateEvent
- [x] EntityEvent.LivingEvent.PlayerEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.AchievementEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.AnvilRepairEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.ArrowLooseEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.ArrowNockEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.AttackEntityEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.BonemealEvent
- [x] EntityEvent.LivingEvent.PlayerEvent.BreakSpeed
- [ ] EntityEvent.LivingEvent.PlayerEvent.Clone
- [ ] EntityEvent.LivingEvent.PlayerEvent.EntityItemPickupEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.FillBucketEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.HarvestCheck
- [ ] EntityEvent.LivingEvent.PlayerEvent.ItemTooltipEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.LoadFromFile
- [ ] EntityEvent.LivingEvent.PlayerEvent.NameFormat
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerDestroyItemEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerFlyableFallEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.EntityInteract
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.EntityInteractSpecific
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.LeftClickBlock
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.LeftClickEmpty
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.RightClickEmpty
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.RightClickEmpty
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerInteractEvent.RightClickItem
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerOpenContainerEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerPickupXpEvent
- [x] EntityEvent.LivingEvent.PlayerEvent.PlayerSetspawnEvent
- [ ] EntityEvent.LivingEvent.PlayerEvent.PlayerWakeUpEvent
- [x] EntityEvent.LivingEvent.PlayerEvent.RenderPlayerEvent
- [x] EntityEvent.LivingEvent.PlayerEvent.RenderPlayerEvent.Post
- [x] EntityEvent.LivingEvent.PlayerEvent.RenderPlayerEvent.Pre
- [ ] EntityEvent.LivingEvent.PlayerEvent.RenderPlayerEvent.SetArmorModel
- [x] EntityEvent.LivingEvent.PlayerEvent.RenderPlayerEvent.Specials
- [ ] EntityEvent.LivingEvent.PlayerEvent.SaveToFile
- [x] EntityEvent.LivingEvent.PlayerEvent.SleepingLocationCheckEvent
- [x] EntityEvent.LivingEvent.PlayerEvent.StartTracking
- [x] EntityEvent.LivingEvent.PlayerEvent.StopTracking
- [ ] EntityEvent.LivingEvent.PlayerEvent.UseHoeEvent
- [x] EntityEvent.MinecartEvent
- [ ] EntityEvent.MinecartEvent.MinecartCollisionEvent
- [ ] EntityEvent.MinecartEvent.MinecartInteractEvent
- [x] EntityEvent.MinecartEvent.MinecartUpdatedEvent
- [ ] EntityEvent.PlaySoundAtEntityEvent
- [ ] EntityEvent.ZombieEvent
- [ ] EntityEvent.ZombieEvent.SummonAidEvent
- [ ] EntityViewRenderEvent
- [ ] EntityViewRenderEvent.CameraSetup
- [ ] EntityViewRenderEvent.FogColors
- [ ] EntityViewRenderEvent.FogDensity
- [ ] EntityViewRenderEvent.FOVModifier
- [ ] EntityViewRenderEvent.RenderFogEvent
- [x] ExplosionEvent
- [x] ExplosionEvent.Detonate
- [x] ExplosionEvent.Start
- [ ] FluidContainerRegisterEvent
- [ ] FluidEvent
- [ ] FluidEvent.FluidDrainingEvent
- [ ] FluidEvent.FluidFillingEvent
- [ ] FluidEvent.FluidMotionEvent
- [ ] FluidEvent.FluidSpilledEvent
- [ ] FluidRegisterEvent
- [ ] FMLNetworkEvent<T>
- [ ] FMLNetworkEvent<T>.ClientConnectedToServerEvent<T>
- [ ] FMLNetworkEvent<T>.ClientDisconnectionFromServerEvent<T>
- [x] ~~FMLNetworkEvent<T>.CustomPacketEvent<T>~~
- [x] ~~FMLNetworkEvent<T>.CustomPacketEvent<T>.ClientCustomPacketEvent<T>~~
- [x] ~~FMLNetworkEvent<T>.CustomPacketEvent<T>.ServerCustomPacketEvent<T>~~
- [x] ~~FMLNetworkEvent<T>.CustomPacketRegistrationEvent<T>~~
- [ ] FMLNetworkEvent<T>.ServerConnectionFromClientEvent<T>
- [ ] FMLNetworkEvent<T>.ServerDisconnectionFromClientEvent<T>
- [ ] ForceChunkEvent
- [ ] FOVUpdateEvent
- [x] GuiOpenEvent
- [x] GuiScreenEvent
- [x] GuiScreenEvent.ActionPerformedEvent
- [x] GuiScreenEvent.ActionPerformedEvent.Post
- [x] GuiScreenEvent.ActionPerformedEvent.Pre
- [ ] GuiScreenEvent.BackgroundDrawnEvent
- [x] GuiScreenEvent.DrawScreenEvent
- [x] GuiScreenEvent.DrawScreenEvent.Post
- [x] GuiScreenEvent.DrawScreenEvent.Pre
- [x] GuiScreenEvent.InitGuiEvent
- [x] GuiScreenEvent.InitGuiEvent.Post
- [x] GuiScreenEvent.InitGuiEvent.Pre
- [x] GuiScreenEvent.KeyboardInputEvent
- [x] GuiScreenEvent.KeyboardInputEvent.Post
- [x] GuiScreenEvent.KeyboardInputEvent.Pre
- [x] GuiScreenEvent.MouseInputEvent
- [x] GuiScreenEvent.MouseInputEvent.Post
- [x] GuiScreenEvent.MouseInputEvent.Pre
- [ ] GuiScreenEvent.PotionShiftEvent
- [ ] InitMapGenEvent
- [x] InputEvent
- [x] InputEvent.KeyInputEvent
- [x] InputEvent.MouseInputEvent
- [ ] LootTableLoadEvent
- [ ] ModelBakeEvent
- [x] MouseEvent
- [x] OreGenEvent
- [x] OreGenEvent.GenerateMinable
- [x] OreGenEvent.Post
- [x] OreGenEvent.Pre
- [x] OreRegisterEvent
- [x] PlayerEvent.ItemCraftedEvent
- [x] PlayerEvent.ItemPickupEvent
- [x] PlayerEvent.ItemSmeltedEvent
- [x] PlayerEvent.PlayerChangedDimensionEvent
- [ ] PlayerEvent.PlayerLoggedInEvent
- [ ] PlayerEvent.PlayerLoggedOutEvent
- [ ] PlayerEvent.PlayerRespawnEvent
- [ ] PotionBrewEvent
- [ ] PotionBrewEvent.Post
- [ ] PotionBrewEvent.Pre
- [ ] RenderBlockOverlayEvent
- [x] RenderGameOverlay
- [x] RenderGameOverlay.Post
- [x] RenderGameOverlay.Pre
- [ ] RenderHandEvent
- [ ] RenderItemInFrameEvent
- [x] RenderLivingEvent<T>
- [x] RenderLivingEvent<T>.Post<T>
- [x] RenderLivingEvent<T>.Pre<T>
- [x] RenderLivingEvent<T>.Specials<T>
- [ ] RenderWorldLastEvent
- [x] ScreenshotEvent
- [x] ServerChatEvent
- [ ] SoundEvent
- [ ] SoundEvent.PlaySoundEvent
- [ ] SoundEvent.SoundLoadEvent
- [ ] SoundEvent.SoundSetupEvent
- [ ] SoundEvent.SoundSourceEvent
- [ ] TextureStitchEvent
- [ ] TextureStitchEvent.Post
- [ ] TextureStitchEvent.Pre
- [x] TickEvent
- [x] TickEvent.ClientTickEvent
- [x] TickEvent.PlayerTickEvent
- [x] TickEvent.RenderTickEvent
- [x] TickEvent.ServerTickEvent
- [x] TickEvent.WorldTickEvent
- [ ] UnforceChunkEvent
- [x] WorldEvent
- [ ] WorldEvent.ChunkEvent
- [ ] WorldEvent.ChunkEvent.ChunkDataEvent
- [ ] WorldEvent.ChunkEvent.Load
- [ ] WorldEvent.ChunkEvent.Unload
- [x] WorldEvent.CreateSpawnPosition
- [ ] WorldEvent.InitNoiseGensEvent<T>
- [x] WorldEvent.Load
- [ ] WorldEvent.PotentialSpawns
- [ ] WorldEvent.SaplingGrowTreeEvent
- [ ] WorldEvent.Save
- [x] WorldEvent.Unload
- [ ] WorldTypeEvent
- [ ] WorldTypeEvent.BiomeSize
- [ ] WorldTypeEvent.InitBiomeGens

**Comment by ProfessorProspector** [comment]
Suggesting BlockEvent.AttemptBlockMine

Is fired when you attempt to start breaking a block. Can be used to completely prevent you from even starting to break a block.

**Comment by darkhax** [comment]
@ProfessorProspector Sounds like a good idea, however this functionality is already offered by Forge's BreakSpeedEvent. One issue with that event is that it doesn't take creative into account.

**Comment by ProfessorProspector** [comment]
Ah, didn't know that. Is that a problem though that this is already offered by forge?

**Comment by darkhax** [comment]
@ProfessorProspector No, it being in forge is not an issue. However we don't want duplicate functionality.

**Comment by iLexiconn** [comment]
Whoops, I thought it wasn't an event and told him to comment of this issue. Sorry :P

**Comment by ProfessorProspector** [comment]
Oh I see. I mean they have different applications. Like you said, this would take creative into account.

**Comment by darkhax** [comment]
@ProfessorProspector Well not taking creative into account is something I would classify as a bug in forge. We won't have that bug ;p

**Comment by Thog** [comment]
We will need events for enchanting and repairing that Forge doesn't provide

**Comment by iLexiconn** [comment]
Give me a nice name and I'll add them. :)

**Comment by darkhax** [comment]
@Thog @iLexiconn EnchantItemEvent for when an item is enchanted. RepairItemEvent for when an item is repaired. I would also like an EnchantmentLevelEvent which allows the level of an enchantment to be modified. For example, if the player is holding X item in their inventory, then fire aspect gets +1 level.

**Comment by rubensworks** [comment]
@Thog @darkhax I'd be happy to port my LivingEnchantmentLevelEvent I PR'd to Forge a while ago: MinecraftForge/MinecraftForge#2839
I don't think that PR is ever going to get merged anyways...

**Comment by darkhax** [comment]
@rubensworks that would be greatly appreciated. Your event is something I have personally been wanting for a long time in forge.

**Comment by modmuss50** [comment]
It doesnt matter if forge has an event or not. We do not need to compare this to forge.

**Comment by Victorious3** [comment]
My two cents: Note that Forge's events are only as fast as they are because they use ASM to inline calls, I'd definitely do the same. The usage with the lambda callback is all nice and fancy but it lacks a certain convenience compared to Forge's @EventHandler, and I don't know how well a lambda works in terms of ASM optimizations.

**Comment by darkhax** [comment]
I completely agree with you on this @Victorious3 we are working on something new, should be in place later today.

**Comment by shadowfacts** [comment]
I am working on PRing my ScreenshotEvent

**Comment by Rushmead** [comment]
Claiming the CommandEvent

**Comment by Rushmead** [comment]
Thoughts on a ArmorEquipEvent(Possibly an ArmorUnequipEvent aswell)?

**Comment by Rushmead** [comment]
Claiming the ArmorEquip.Equip and ArmorEquip.Unequip events

**Comment by The-Fireplace** [comment]
I will see about GuiScreenEvent.InitGuiEvent.Post. No promises, but I will try.

**Comment by shadowfacts** [comment]
@The-Fireplace Is it really necessary? Is there any not niche use case?

**Comment by The-Fireplace** [comment]
@shadowfacts I just looked at it, and asked myself the same thing. GuiEvent.Init is called after the button list is cleared, so there isn't any reason to add it.

**Comment by darkhax** [comment]
I am going to claim the render event. I have pretty big plans for it, so I am going to create a pull request.

**Comment by iLexiconn** [comment]
What render event, lol

**Comment by darkhax** [comment]
@iLexiconn I added a `- claimed by Darkhax` to the ones I plan to tackle. I am planning to merge a bunch of it together, and then expand some. Here is the list of what it will look like. 

- RenderEvent - The parent class
- RenderEvent.Entity - Entities
- RenderEvent.Shadow - Shadows, because they're not part of entities aparently
- RenderEvent.Layer - Direct access to RenderLayer allowing for some cool changes

I am a bit concerned that having so many render events will slow down rendering, however keep in mind that firing an event is basically free for us right now, and will be even closer to free once @Victorious3 PRs the ASM based events.

**Comment by Rushmead** [comment]
MINE:
 EntityEvent.EntityMountEvent
 EntityEvent.EntityStruckByLightningEvent
 EntityEvent.EntityTravelToDimensionEvent

**Comment by 4rz0** [comment]
In KeyPressEvent, will there be specific support for the modifier keys?
Also, will there be a system for a mod to register a new keybind and if that's pressed, said mod will get an event back?

**Comment by gegy1000** [comment]
Claiming
PlayerEvent.ItemCraftedEvent,
PlayerEvent.ItemPickupEvent,
and PlayerEvent.ItemSmeltedEvent

**Comment by darkhax** [comment]
Claiming 
```
 EntityViewRenderEvent
 EntityViewRenderEvent.CameraSetup
 EntityViewRenderEvent.FogColors
 EntityViewRenderEvent.FogDensity
 EntityViewRenderEvent.FOVModifier
 EntityViewRenderEvent.RenderFogEvent
```

**Comment by coolsquid** [comment]
Claiming all the living events. Might work on some world gen events when I'm done, so please tell me if you're doing those.

Also, I think @strikingwolf is doing player events.

**Comment by ostenvighx** [comment]
Gonna take a shot at the RenderGameOverlay events.

**Comment by darkevilmac** [comment]
Gonna go ahead and port my PlayerSetSpawnEvent.

**Comment by Caellian** [comment]
### Something drastic needs to change about events.
#### 1. We don't want to copy-paste all Forge events as it's one of the reasons why it's so slow.
#### 2. We don't want to handle events which are not being used.
#### 3. We want to allow people to add new events easily without using the patching system.
I'm currently looking into how to accomplish the third. ASM would be amazing, but it's a bit hard to use, breaks every version update and is usually just annoying.

Any suggestions are welcome. I'm currently looking into [Callback Injectors](https://github.com/SpongePowered/Mixin/wiki/Advanced-Mixin-Usage---Callback-Injectors) from Mixins.
