### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by iLexiconn** [OpenModLoader/OpenModLoader#12]
Snackbar notification system

**Comment by ProfessorProspector** [comment]
Oh yes please! Like the one that ChatFlow adds. Also if this gets added, could bed messages be moved to it rather than chat? :P

**Comment by iLexiconn** [comment]
Good idea! I'll add that as soon as it's implemented. (Working on it right now)

**Comment by ProfessorProspector** [comment]
Awsesome! Make sure it supports colours too. Also, what if two notifications are displayed at once? Will there be a backlog or will it just replace the last one?

**Comment by iLexiconn** [comment]
It supports colors and the notifcations wait in a queue if there's already one on the display.

**Comment by ProfessorProspector** [comment]
Sounds awesome. Also something to keep in mind, you know how various mods use the "no-spam chat" thing where it deletes the old chat message before making a new one (for updating values or something), could there be a feature for this in forge, as well as for the notification system?

**Comment by iLexiconn** [comment]
There's already a chat ever in OML, I'll also add an event like that for the notificatins that do the same. :)

**Comment by darkhax** [comment]
Could you explain in further detail what this actually is?

**Comment by ProfessorProspector** [comment]
Do you use android? It's like the notifications that pop up on the screen for a second or two. It's basically an alternative to using chat for notifications, and save the chat for, you know, chat.

**Comment by darkhax** [comment]
Oh, I see. So this would basically be like the achievement HUD. I had [something similar](https://github.com/Darkhax-Minecraft/Bookshelf/blob/e74f7a71f9206966ce7b39fec9e3dba11a406a86/src/main/java/net/darkhax/bookshelf/client/gui/GuiNotification.java) implemented in Bookshelf a for 1.7.10 Code probably still works if the rendering was switched to the a state manager.

**Comment by ProfessorProspector** [comment]
Here is a gif @iLexiconn posted https://gfycat.com/UnfortunateConfusedGeese

**Comment by darkhax** [comment]
Ah, neat. I like that. My system is basically a copy of MC's achievement notification :p

**Comment by ProfessorProspector** [comment]
Hey lexicon, what about displaying an itemstacks as a prefix to a notification? That would be very useful. If that happens, achievements could use the universal notification system then

**Comment by darkhax** [comment]
While the notification system is cool, we shouldn't rewrite vanilla to run through it. Actual features like that should be handled by the mods.

**Comment by iLexiconn** [comment]
@darkhax I didn't 'rewrite' anything for it.
@ProfessorProspector You already can. (I think)
