### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by shadowfacts** [OpenModLoader/OpenModLoader#22]
OML should have a standardized config system for all mods to use.

My suggestion is [Typesafe Config](https://github.com/typesafehub/config).

**Comment by iLexiconn** [comment]
Typesafe looks like a good idea!

**Comment by ProfessorProspector** [comment]
The config system should be designed to work well with a gui, rather than how forge had to build the gui based on the config format.

**Comment by ProfessorProspector** [comment]
Also is there a way to have enum values as config objects in forge? That would be a very useful thing to have.

**Comment by iLexiconn** [comment]
It doesn't really matter if we can just get enough info from the config (and we can with typesafe)

**Comment by iLexiconn** [comment]
On a second thought, I think we just have to use JSON. People are familiair with it and we already have the dependency for it.

**Comment by skyem123** [comment]
JSON is not very user-friendly, it's designed for computer data transfer not human to computer interface.

**Comment by shadowfacts** [comment]
Yeah, as Skye said, JSON is designed for computers (and programmers) to work with not end users. 

TypeSafe Config using [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md), a superset of JSON with numerous improvements over it, including a much cleaner syntax making it easier for end users to understand.

Additionally, one major thing that JSON lacks which would make it hard to have user-friendly configuration files, is comments (which HOCON/TypeSafe config do have). A property name is nowhere as informative as a property name and a comment describing what it does.

**Comment by skyem123** [comment]
There's also stuff like [YAML](http://yaml.org/) and [SDLang](https://sdlang.org/), which try to be user friendly.
