### ISSUE TITLE
Packet system

### ISSUE THREAD

**Issue by iLexiconn** [OpenModLoader/OpenModLoader#27]
I was thing about something like [this](https://github.com/iLexiconn/LLibrary/blob/1.9.4/src/main/java/net/ilexiconn/llibrary/server/network/AbstractMessage.java), from LLibrary.

**Comment by shadowfacts** [comment]
I think something like [LambdaNetwork](https://github.com/elytra/LambdaNetwork) is better because it's got a nice builder model making it easier to create and send packets quickly and prevents modders from needing to write their own serialization/deserialization code for the majority of packets.

**Comment by iLexiconn** [comment]
That looks really neat! I think we'll go with something like that.
