### ISSUE TITLE
Javadocs?

### ISSUE THREAD

**Issue by ConnorHartley** [OpenModLoader/OpenModLoader#40]
Where are they?

**Comment by darkhax** [comment]
They are currently available through the code, and once we have public builds you will be able to download them directly. They will probably also be hosted on our site if @modmuss50 wants to set that up.

**Comment by phase** [comment]
[They](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/OpenModLoader.java)
[are](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/ISidedHandler.java)
[not](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/registry/GameRegistry.java)
[available](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/modloader/ManifestModContainer.java)
[through](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/modloader/Version.java)
[the](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/modloader/IMod.java)
[code](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/modloader/DependencySorter.java).

The only class I can see that is somewhat well documented is [ModLoader](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/modloader/ModLoader.java). Everything else is lacking comments, and the commit messages make less sense than mashing my keyboard.
Like, really, what on earth is [`¯\_(ツ)_/¯`](https://github.com/OpenModLoader/OpenModLoader/commit/b9c0533a3b7ccafee06f4d78c0af525d62bc5f11)? The commit message gives no description of what the commit changes, and the body states, verbatim, "Thank @CoolSquid." That really tells me a lot about what code has been changed.

**Comment by darkhax** [comment]
[A](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/event/Event.java)
[lot](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/event/EventBus.java)
[of](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/config/Config.java)
[the](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/event/impl/RenderEvent.java)
[code](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/event/impl/ScreenshotEvent.java)
[is](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/event/impl/ExplosionEvent.java)
[documented](https://github.com/OpenModLoader/OpenModLoader/blob/master/src/main/java/xyz/openmodloader/launcher/strippable/Strippable.java)

There are certainly large holes in our documentation and inconsistencies here and there, but they are being sorted out. Some of the undocumented code is very volatile, so I haven't had a chance to add docs without causing conflicts for the rest of the team. That said, we definitely have a huge problem with certain developers disregarding our policies, and we are working on a solution for that right now. I was actually in the middle of writing our contributing file when you wrote your comment.

**Comment by phase** [comment]
I can't wait for that file!

**Comment by ConnorHartley** [comment]
I agree.
