### ISSUE TITLE
Network patches incomplete, causes compile issues

### ISSUE THREAD

**Issue by darkhax** [OpenModLoader/OpenModLoader#75]
The class NetHandlerPlayServer has several issues. It seems that the patch for it was not committed. 

Line 726 `this.serverController.getPlayerList().sendChatMsgImpl(var6, false);`
The method sendChatMsgImpl(ICommandSender, ITextComponent, boolean) in the type PlayerList is not applicable for the arguments (TextComponentTranslation, boolean)

Line 158 `var3.connection = this;` 
Type mismatch: cannot convert from NetHandlerPlayServer to net.minecraft.network.NetHandlerPlayServer

**Comment by coolsquid** [comment]
What the actual... Why the heck doesn't NetHandlerPlayServer.java.patch show up in my Git commit GUI thing? Either way, should be fixed by b167ca88cfea401ad6b77a39891f02785b314efa.
