### ISSUE TITLE
Enforced SemVer

### ISSUE THREAD

**Issue by darkhax** [OpenModLoader/OpenModLoader#8]
Due to the way we are handling version numbers (through the json file) we can split it up into three different parts. This would allow us to enforce a 3 number [SemVer](http://semver.org/) system. 

```
{
    "major" : 1,
    "minor": 0,
    "patch": 27
}
```

**Comment by shadowfacts** [comment]
Mandatory SemVer would be awesome, however I think having a whole JSON object instead of just one string is unnecessary.

**Comment by ProfessorProspector** [comment]
There's no real good way to do it otherwise. I like this idea +1

**Comment by skyem123** [comment]
@shadowfacts, I think the idea of splitting it up would be to make sure that people don't abuse the version string.

However, if it's split up, then the extra details that SemVer allows should probably be added somehow, to allow for stuff like build numbers and other details that people pack in.

**Comment by iLexiconn** [comment]
I don't think it's a good idea. I often use 'dev' as version string so I don't mess up and release it.

**Comment by shadowfacts** [comment]
SemVer has support for extra labels. This can be something dev (so `1.2.3-dev`) or something like Maven's SNAPSHOT  (`1.2.3-SNAPSHOT`).

**Comment by iLexiconn** [comment]
Still don't think it's a good idea :p

**Comment by skyem123** [comment]
Here's a random idea: how about a "SemVer" object for compatibility checking, yet let the mod makers use their own version string?

**Comment by iLexiconn** [comment]
Ill make something like that. Simver will still be optional though.

**Comment by shadowfacts** [comment]
If we do make SemVer optional, we'll have some crazy-ass system like for for parsing versions and dealing with version ranges and matching instead of something, [nice and simple and standardized](https://github.com/shadowfacts/ShadowLib/tree/master/src/main/java/net/shadowfacts/shadowlib/version).

**Comment by iLexiconn** [comment]
We can add a simple regex check for that

**Comment by skyem123** [comment]
That's why a semver object should be for version checking, yet if a crazy modder, such as @Victorious3 (oh their wacky version number system) wants to have their own version string, they can.

**Comment by iLexiconn** [comment]
Uh, the current version checker (not on repo yet) supports all kinds of version strings.

**Comment by skyem123** [comment]
The advantage of semver is that you can assume that stuff is compatible if the patch version is the same, and backwards compatible if the minor version is the same.

**Comment by iLexiconn** [comment]
You're right. Let's just do it.

**Comment by Victorious3** [comment]
@skyem123 What I'd do then is to just leave it at 0.0.0 for eternity because my system is clearly the better one! 😆 
In all honesty though, this:
>The advantage of semver is that you can assume that stuff is compatible if the patch version is the same, and backwards compatible if the minor version is the same.

sounds like a unicorn to me.

**Comment by skyem123** [comment]
Well... it only works if people respect the system.
1.0 is assumed to be incompatible completely with 2.0
Stuff that relies on 1.1 can be compatible with 1.2 (one way).
1.1.0 is compatible with 1.1.1 (both ways), there's just bug fixes.
