### ISSUE TITLE
Power API - Claimed by Caellian & Strikingwolf

### ISSUE THREAD

**Issue by Caellian** [OpenModLoader/OpenModLoader#87]
I am aware of gazillion different power systems out there and how OML does not intend to force it's own power system (which I agree with). However, I do think that some code base which would be common to all power systems would be useful for developers down the road.

Why add this?
Forge has many different power systems. Some are newer, some have sticked around for ages. None of them worked together properly when they were made and it actually took them ages to achieve compatibility (If we ignore complete nerfing issues and them being overpowered in most cases).
Because of this I created the Fuel Registry which adds a lot of stability.

What I want to introduce is code base for adding different power systems. It will not restrict them in any way and will merely be there so they can work together properly and recognize each other.

Introduction of PowerAPI will make power systems less buggy and predictible thus making it easier for mod developers to fix issues they have.

Here is what I wish to add:

- Consumer interface - For blocks and items like Furnaces, Drills, ...
- Container interface - Batteries, more advanced machines, wires...
- Producer interface - Generators, solar panels, ...
- Machine interface - handles GUI and container stuff which removes the need for 3 classes for one machine block unlike Forge (have to still check if this is possible, would it be flexible enoug and things...).

These would introduce simple methods like "getPower" and "sendPower", the way power is handled internally is up to developers.

- Abstract implementation of SI Units and NBT Handler for storing them.
- Abstract code base for Storage blocks
- Code to make conversion easier but mods will still have to handle it on their own

While I'll be writing these I'll be looking at RP, IC2, BuildCraft (and some others mods introducing power systems likely) and make sure all of these would work with out PowerAPI.

So I'm asking for a permission here before I write this code as I know this was argued over a lot by Forge team and they decided to not add PowerAPI because they weren't able to write it to be flexible enough.

This API would likely be as big as this issue, but would take a lot of planning from my side. I won't be hasty with it, if it's done, it will be done properly.

**Comment by phase** [comment]
I'm completely for this. The more that is baked into the API, the more tools developers have to make better mods. One complete power system or an abstract system would greatly help developers.

**Comment by Caellian** [comment]
I don't wish to add a complete power system (maybe to example mod), but I'm voting for an abstract API which would make other power systems more stable.

**Comment by skyem123** [comment]
How about something like a base for connections in general?
Like, something that many mods add is connections, one type of which is power.
There are things other than power, that could benefit from help inside of the mod loader / API / thing.

Similar to power is data, like the cables from OC and CC. However, it is different in important ways (mainly the fact that there's a lot of data), which might be impractical.
There is also stuff like fluid transport, which is similar to power in some ways.
Then there is item transport, which again probably won't benefit as much from this, but it's probably worth thinking about.

I'm probably rambling about something I don't have much of an understanding on, but hopefully I said something useful / interesting / not entirely stupid. :stuck_out_tongue:

**Comment by darkhax** [comment]
If this were to be implemented, it would have to be done very carefully. Almost anything we could add would enforce something in some way. For example, the interfaces you describe would restrict the type of parameters that could be used, by this I mean it would either not support transfer resistance, or enforce transfer resistance. The idea of making all power API compatable with each other also enforces the idea that they should be compatible. Multiple power API that have little to no interaction is not a bad thing, and as shown in Infinity Hard Mode, it can be used to separate early/mid and late game content.

**Comment by Strikingwolf** [comment]
@darkhax What @Caellian proposes here is a way to make it _easy_ to make them compatible. But the mods would have to actually do any compatibility in their own right. Though I do believe there should be a way for a mod author to say 
> "Don't let this be made compatible except with [x, y, z...]" 
so that a mod author with another power system can't link them or worse a random author link two power systems that aren't theirs

**Comment by skyem123** [comment]
Um... I think the idea of restricting what people can do goes against the whole point of modding. :stuck_out_tongue:

**Comment by Strikingwolf** [comment]
@skyem123 it doesn't restrict what people can do in fact, they could ASM that out or figure out another method of preventing conversion. What it does is prevent someone from breaking a mod whose author wants it to work in isolation from others unless they have a good reason and it isn't on a whim

**Comment by skyem123** [comment]
@Strikingwolf, Well... It should be possible for people to convert between energy systems, as long as they are able to implement everything for the systems being converted between.

Also, how about having a more generic network / connection / thing that could be used for more than just power?

**Comment by Caellian** [comment]
Darkhax, my currently planned system has no such restrictions. Both units and conductors would have "properties" (resistance/conductivity, magnetic permeability,...) which is a very scalable system and basically means that mods could use wires from different mods if those wires have needed properties for flow calculation. 

@skyem123 I know what you meant by what you initially said. I would call such an API "Flow API" and it would likely be a good idea to base "Power API" on it. This would add an additional step to development of this API, but would in return make development of Fluid API easier a tiny bit and make for more stable code. 

Further, it would be a good idea to give devs "restrict all power interaction", "blacklist power interaction for mods" and "whitelist power interaction for mods" options so they have full control over what is done with their power systems. 
Great example of this is EE3 mod where EMC can be using Power API and one would want to prevent all conversion to and from EMC because people could use solar panels and generators to get better resources.

**Comment by skyem123** [comment]
@Caellian, the problem is with allowing mods to stop other mods from interacting with their power systems is that people who really want to do it use a power system will use reflection / ASM, which is never pretty.

**Comment by Caellian** [comment]
Problem is that people are idiots. We can fool proof every part of Minecraft as much as we want and someone will still come up with a way to screw things up.
Code will be designed so people with  brain can use it. ASM can't be avoided and if someone wants to, he/she is free to use it. Permission system is there just so other mod developers know they aren't supposed to interact with your power type.
Realistically, who is preventing someone to make a mod that converts RP to EMC? Who is preventing someone to write a mod which gives you a stack of diamonds whenever you need it?
Mods should be written with logic in mind - if a mod developer said "Don't touch my power type, it will make both of our mods unstable." them you're gonna guess it's not a smart idea to do that.

In most cases, Power API would allow you to interact with other power systems without accessing other mod source code.

**Comment by skyem123** [comment]
To be honest, I think that conversion should happen manually, and shouldn't be automatic. 
If people bother to write logic to conversion , that should be enough. If a modder didn't want to let other mods use their power system, then they shouldn't use the API.

**Comment by Caellian** [comment]
We all agreed that conversion will be manual right at the beginning. There is too much uncertainty to make an automatic system. We were discussing about allowing power systems to manage conversion registration and prevent converters from being registered if the power system says so.
If someone doesn't want his/her power system from being used at all by other mods, he will be able to remove it from power registry so that other mods can't refrence it without source code which would be the same as not using the API but developer would have a benefit of stable power system infrastructure.

**Comment by skyem123** [comment]
That makes sense, however... If people block registering of converters, then it's still possible to make a converter by using normal power APIs. 

If you're talking about letting mods register their power system and also control what mods use it, it defeats the purpose of a registry. I think that if a mod wants to control that, then they shouldn't register it publicly, and handle the other mods themselves.

**Comment by Caellian** [comment]
@skyem123 you're confusing me.
If author blocks converter registration, only way to do it is using source code of that mod and doing things that aren't supposed to be done.
If developer decides to exclude his power system from registry, again, only way you can access it is source code of his/her mod.
This API doesn't prevent people from being stupid and breaking mods, it makes it easier for power systems to interact without having to access each others sources (+ stable framework with well written iterators, stream support, networking, automatic unit management, converters,...).
I'm sure if you put your mind to it that you'll be able to think of more than dozen ways to break it as there is for literally every code ever written. There's a lot of things mod developers already do with other mods that aren't supposed to be done, there is no way of preventing them.
Stuff like this can be discussed on pull request when it's done and we can actually see the code. I have a lot of things planned in my head that aren't here because I don't feel like writing a Bible. Just so it's known, I started planning this API out on paper already, but until I can access my development environment and actually write code, things will be uncertain.

**Comment by skyem123** [comment]
@Caellian, the main thing I am confused about the idea that allowing mods to stop other mods from registering "power converters" will make anything better.
All that a mod needs to make a power converter is input of one type, and output of another type.
From what I can understand, the point of registering a power converter would be to reduce any possible strangeness that could occur.
If a mod decides to only block properly registered "power converters", then the only way to do it would be manually, which would defeat the purpose of registering them!

**Comment by Strikingwolf** [comment]
@skyem123 by blocking power converters you'd also implicitly be blocking anything else that would "take" your power. As otherwise you could do it manually as you said.

**Comment by Caellian** [comment]
Power converters exist so one could for example generate one type of energy and use it to power a machine using other type of energy.
If mod author decides to block power conversion for his mod then it shouldn't be done. If someone does is manually and/or overrides power API then it's his/her fault if something goes wrong. 

I understand what you're saying, but manually doing things with power API shouldn't be done unless you're 100% sure that what you're doing is OK and will not break.
What you're suggesting goes somewhere along the lines of rewriting Swing exactly as it is - you should probably avoid wasting your time and Oracle really can't prevent you from

**Comment by skyem123** [comment]
@Caellian, that's why you shouldn't encourage people to manually go around artificial restrictions.

**Comment by Caellian** [comment]
@skyem123 How am I encouraging them? What are my alternatives? I decided to add blacklists so devs could nicely say in log files "hey, you shouldn't do that", I could add register method overload with boolean which allows you to force register converter, that's about as much as it would make sense to do.

**Comment by Caellian** [comment]
@skyem123 How am I encouraging them? What are my alternatives? I decided to add blacklists so devs could nicely say in log files "hey, you shouldn't do that", I could add register method overload with boolean which allows you to force register converter, that's about as much as it would make sense to do.

**Comment by Caellian** [comment]
TODO:

Difference between conductor capacity and transfer speed.

Add converter of actual speed to block movement where speed of sound is one block per tick speed.

Different transfer handlers - smart/network TH, potential equalization TH, forward TH (packet movement direction might complicate things). Abstract classes.

Think out of the box and hacky - transferring power without conductors; multiblock machines (How would IO work?).

Determine exact moment when power is converted if machine needs another type. Does returning power to wires containing different power type convert it to that type automatically or can wires conduct different types of power simultaneously (add option for developers to choose). Do power types interact in wires/conductors, if so, how? 

Go trough most existing (Forge only) power types multiple times to make sure stuff can work.

**Comment by Victorious3** [comment]
To quote myself:
> Power isn't that different, I mean, what's "power", really? Remember Red Power? I don't think you could fit a propagating system like that into a universal API. The best you can end up with is a really boring one like RF (no offense, but it is boring). I think those are better as mods, as it is today. Let the "market" decide what solution is best instead of assuming one and then limit people's choices on either of these. Perhaps you could come up with a power conversion API.

**Comment by Strikingwolf** [comment]
@Victorious3 I think if you read through what he has currently you could form a better opinion of if it's possible

At this point I'm more worried about it being boilerplate heavy

**Comment by Caellian** [comment]
Power API at this point really supports anything, and I'll likely add some default classes which seem to be very common amongst different power systems. Power API isn't as boilerplate heavy as Flow API is and I guess it's okay for Flow API to be so because it really adds support for transferring and/or storing anything that can be stored (but doesn't have to) in NBT format and allows mods to interact with those systems without including sources/api of the other mod.

I plan on using Flow API for: Power API, Fluid/Liquid API (depends on adding gasses and plasmas), item pipes (not writing an API for that {yet, :laughing:}), some other stuff that I can't even think of yet.
Gui API will also use some parts of Flow API to interact with containers.

P.S. - Discussion on Discord#development which should clarify some things (and also TODO!): http://hastebin.com/ijamalomoj.vbs:laughing:
