### ISSUE TITLE
TileEntity interface

### ISSUE THREAD

**Issue by Caellian** [OpenModLoader/OpenModLoader#92]
This would allow interfaces to extend TileEntity and add default methods using TileEntity methods.
TileEntity is currently an abstract class in Minecraft which doesn't extend or implement anything. I don't see a scenario where TileEntity class implementing our interface would be harmful (as we are talking about implementation, not extension).

Either way, I wanted to be sure everyone agrees with this change. It would help me with writing Flow API and it doesn't bother anyone or break anything, but it still is a vanilla game change.

Following methods would be in this interface:
- addInfoToCrashReport
- getBlockMetadata
- getBlockType
- getDisplayName
- getDistanceSq
- getMaxRenderDistanceSquared
- getPos
- getUpdatePacket
- getUpdateTag
- getWorld
- hasWorldObject
- invalidate
- isInvalid
- markDirty
- onlyOpsCanSetNbt <- amazing mapping that one
- readFromNBT
- recieveClientEvent
- setPos
- setWorldObj
- updateContainingBlockInfo
- validate
- writeToNBT

Following ones would benefit from documentation as they aren't mapped:
- func_189667_a <- handles TileEntity rotation
- func_189668_a <- handles TileEntity mirroring
- func_190200_a <- creates TileEntity from NBTTagCompound
- func_190201_b <- setWorldObj for Signs (this is pointless, should I even add it to the interface?)

**Comment by Caellian** [comment]
Here is an example where this would be useful:
<a href="http://i.imgur.com/rKklr39.png">
  <img src="http://i.imgur.com/rKklr39.png" />
</a>

**Comment by shadowfacts** [comment]
The problem with this is due to the interface methods having the names as the TileEntity methods, when the TileEntity class is reobfuscated the TileEntity interface methods won't be, causing the interface methods to be unimplemented at runtime causing AbstractMethodErrors.

(This might not be true of ModGradle, but this is how it works in ForgeGradle)

**Comment by Victorious3** [comment]
While generally a neat idea, I dont think this change is necessary. It's also a risky one, what if they ever decide to do something with it an interface can't do? I wouldn't want to be the one refactoring that one...
Besides, what you really want are proper traits, and at that point you may want to consider using something that *isn't java* like scala or Kotlin. Forge supports scala out of the box, I think we should do the same.

**Comment by Strikingwolf** [comment]
I agree we should support scala out of box, and if we do that means we can use Scala in our codebase, as it's really interoperable with Java anyway

**Comment by Caellian** [comment]
The sad truth is that a single Trait would fix this, but we can't switch project to Scala for just one trait.

**Comment by Caellian** [comment]
Only way to solve this (that I can think of) is to use Scala traits.

**Comment by DiMuRie** [comment]
I am interesed the most in :
readFromNBT
And
writeToNBT

**Comment by Caellian** [comment]
Those two are basically the reason why I created this issue. This issue can't be fixed with Java and it's silly to switch to Scala because on one class.
Besides, switching to Scala would do this project more harm than good.

This can't be implemented with patches because methods of said interface wouldn't reobfuscate properly thus making code impossible to recompile.
